version: '2'
services:
    triip_chainnet-app:
        image: triip_chainnet
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://triip_chainnet-postgresql:5432/triip_chainnet
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    triip_chainnet-postgresql:
        extends:
            file: postgresql.yml
            service: triip_chainnet-postgresql
